# Copyright (c) 2021 Graphiant Inc.
# All rights reserved
#
# GitLab CI/CD pipeline as code
#
include:
  - local: ${CI_PROJECT_DIR}/pipelines/docker.yml
    rules:
      - if: $DONT_INCLUDE_DOCKER == "true"
        when: never
      - if: $CI_PIPELINE_SOURCE == "schedule" || ($CI_PIPELINE_SOURCE == "pipeline" && $FROM_CRONUS == 'true') || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api"
        when: never
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_COMMIT_BRANCH =~ /^(feature|hotfix)\/.*/
  - local: ${CI_PROJECT_DIR}/pipelines/run.yml

variables:
  RUNNER_TAG: gcs-python-builder

# Define all stages of CI/CD pipeline.
stages:
  - lint
  - build
  - publish
  - run

lint:
  stage: lint
  trigger:
    include: pipelines/lint.yml
    strategy: depend
  rules:
    - if: $DONT_INCLUDE_LINT == "true"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule" || ($CI_PIPELINE_SOURCE == "pipeline" && $FROM_CRONUS == 'true') || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^(feature|hotfix)\/.*/
