---
- name: Manage Graphiant circuits with static routes
  hosts: localhost
  gather_facts: false
  vars:
    graphiant_host: "https://api.graphiant.com"
    graphiant_username: "{{ vault_graphiant_username }}"
    graphiant_password: "{{ vault_graphiant_password }}"
    
    # Use YAML anchors to avoid repetition
    graphiant_client_params: &graphiant_client_params
      host: "{{ graphiant_host | default(lookup('env', 'GRAPHIANT_HOST')) }}"
      username: "{{ graphiant_username | default(lookup('env', 'GRAPHIANT_USERNAME')) }}"
      password: "{{ graphiant_password | default(lookup('env', 'GRAPHIANT_PASSWORD')) }}"
  
  tasks:
    - name: Configure circuits only (for static routes)
      graphiant.graphiant_playbooks.graphiant_interfaces:
        <<: *graphiant_client_params
        interface_config_file: "configs/sample_interface_config.yaml"
        circuit_config_file: "configs/sample_circuit_config.yaml"
        operation: "configure_circuits"
        state: present
      tags: ['circuits', 'static_routes']
    
    - name: Deconfigure circuits only (removes static routes)
      graphiant.graphiant_playbooks.graphiant_interfaces:
        <<: *graphiant_client_params
        interface_config_file: "configs/sample_interface_config.yaml"
        circuit_config_file: "configs/sample_circuit_config.yaml"
        operation: "deconfigure_circuits"
        state: absent
      when: circuit_cleanup is defined and circuit_cleanup
      tags: ['circuits', 'cleanup']


