---
- name: Final test of Graphiant Ansible Collection
  hosts: localhost
  gather_facts: false
  vars:
    # graphiant_host: "https://api.graphiant.com"
    # graphiant_username: "{{ vault_graphiant_username }}"
    # graphiant_password: "{{ vault_graphiant_password }}"

    # Use YAML anchors to avoid repetition
    graphiant_client_params: &graphiant_client_params
      host: "{{ graphiant_host | default(lookup('env', 'GRAPHIANT_HOST')) }}"
      username: "{{ graphiant_username | default(lookup('env', 'GRAPHIANT_USERNAME')) }}"
      password: "{{ graphiant_password | default(lookup('env', 'GRAPHIANT_PASSWORD')) }}"
  
  tasks:
    - name: Test module parameter validation
      graphiant.graphiant_playbooks.graphiant_global_config:
        <<: *graphiant_client_params
        config_file: "sample_global_prefix_lists.yaml"
        operation: "configure"
        state: present
      ignore_errors: true
      register: test_result
    
    - name: Display test result
      debug:
        msg: 
          - "✅ Graphiant Ansible Collection is working!"
          - "Module loaded: {{ test_result is defined }}"
          - "Error handling works: {{ test_result.failed | default(false) }}"
          - "Expected error: {{ test_result.msg | default('No error') }}"
          - "Full result: {{ test_result }}"
