---
- name: Test Graphiant Ansible Collection
  hosts: localhost
  gather_facts: false
  vars:
    graphiant_host: "https://api.graphiant.com"
    graphiant_username: "{{ vault_graphiant_username }}"
    graphiant_password: "{{ vault_graphiant_password }}"
  
  tasks:
    - name: Test global prefix sets configuration (check mode)
      graphiant.graphiant_playbooks.graphiant_global_config:
        host: "{{ graphiant_host }}"
        username: "{{ graphiant_username }}"
        password: "{{ graphiant_password }}"
        config_file: "configs/sample_global_prefix_lists.yaml"
        operation: "configure"
        state: present
      check_mode: true
      tags: ['test', 'global_config']
    
    - name: Test BGP peering configuration (check mode)
      graphiant.graphiant_playbooks.graphiant_bgp:
        host: "{{ graphiant_host }}"
        username: "{{ graphiant_username }}"
        password: "{{ graphiant_password }}"
        bgp_config_file: "configs/sample_bgp_peering.yaml"
        operation: "configure"
        state: present
      check_mode: true
      tags: ['test', 'bgp']
    
    - name: Test interface configuration (check mode)
      graphiant.graphiant_playbooks.graphiant_interfaces:
        host: "{{ graphiant_host }}"
        username: "{{ graphiant_username }}"
        password: "{{ graphiant_password }}"
        interface_config_file: "configs/sample_interface_config.yaml"
        circuit_config_file: "configs/sample_circuit_config.yaml"
        operation: "configure_interfaces"
        state: present
      check_mode: true
      tags: ['test', 'interfaces']
    
    - name: Test site attachments (check mode)
      graphiant.graphiant_playbooks.graphiant_sites:
        host: "{{ graphiant_host }}"
        username: "{{ graphiant_username }}"
        password: "{{ graphiant_password }}"
        site_config_file: "configs/sample_site_attachments.yaml"
        operation: "attach"
        state: present
      check_mode: true
      tags: ['test', 'sites']


