---
galaxy_info:
  author: Graphiant
  description: "Download the GNOS qcow2 image to the hypervisor"
  company: Graphiant
  license: GPL-3.0-or-later
  min_ansible_version: "2.17"
  galaxy_tags:
    - graphiant
    - gateway
    - naas
dependencies: []
