---
workflow:
  name: Linting
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

default:
  image: python:3.12-slim
  tags:
    - graphiant-default

stages:
  - lint

flake8:
  stage: lint
  script:
    - pip install flake8
    - flake8 ./ansible_collections/graphiant/graphiant_playbooks/plugins/module_utils
    - flake8 ./ansible_collections/graphiant/graphiant_playbooks/tests

pylint:
  stage: lint
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  image: python:3.12-slim
  cache:
    paths:
      - .cache/pip/
      - venv/
      - .pylint_cache/
  script:
    - python3.12 -m venv venv
    - source venv/bin/activate
    - pip3 install -r ansible_collections/graphiant/graphiant_playbooks/requirements.txt
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/ansible_collections/graphiant/graphiant_playbooks/plugins/module_utils
    - pylint --errors-only ./ansible_collections/graphiant/graphiant_playbooks/plugins/module_utils

jinjalint:
  stage: lint
  script:
    - python3.12 -m venv venv
    - source venv/bin/activate
    - pip3 install -r ansible_collections/graphiant/graphiant_playbooks/requirements.txt
    - djlint ansible_collections/graphiant/graphiant_playbooks/configs -e yaml
    - djlint ansible_collections/graphiant/graphiant_playbooks/templates -e yaml

ansible-lint:
  stage: lint
  script:
    - python3.12 -m venv venv
    - source venv/bin/activate
    - pip3 install -r ansible_collections/graphiant/graphiant_playbooks/requirements.txt
    - ansible-galaxy collection install ansible_collections/graphiant/graphiant_playbooks/ --force
    - ansible-lint --config-file ~/.ansible/collections/ansible_collections/graphiant/graphiant_playbooks/.ansible-lint ~/.ansible/collections/ansible_collections/graphiant/graphiant_playbooks/playbooks/

lint-collection-docs:
  stage: lint
  script:
    - python3.12 -m venv venv
    - source venv/bin/activate
    - pip3 install -r ansible_collections/graphiant/graphiant_playbooks/requirements.txt
    - ansible-galaxy collection install ansible_collections/graphiant/graphiant_playbooks/ --force
    - antsibull-docs lint-collection-docs --plugin-docs ~/.ansible/collections/ansible_collections/graphiant/graphiant_playbooks/