AWSTemplateFormatVersion: 2010-09-09
Description: Template for the Graphiant VPC.

Parameters:
  AvailabilityZone:
    Description: Availability zone to create network resources in
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a
  VPCAddressRange:
    Description: The block of addresses that the deployed VPC owns
    Type: String
    Default: 10.0.0.0/16

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        MetadataOptions:
          InstanceMetadataTags: enabled

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCAddressRange
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  IGWRouteV4:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable

  IGWRouteV6:
    Type: AWS::EC2::Route
    Properties:
      DestinationIpv6CidrBlock: ::/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable

  IPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref VPC

  # Subnet stack - cloudinit
  SubnetCloudInit:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      AssignIpv6AddressOnCreation: true
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Select [0, Fn::Cidr: [!GetAtt VPC.CidrBlock, 4, 8]]
      Ipv6CidrBlock:
        !Select [0, Fn::Cidr: [!Select [0, !GetAtt VPC.Ipv6CidrBlocks], 4, 64]]
      VpcId: !Ref VPC

  RouteTableAssociationCloudInit:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetCloudInit

  # Subnet stack - Mgmt
  SubnetMgmt:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      AssignIpv6AddressOnCreation: true
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Select [1, Fn::Cidr: [!GetAtt VPC.CidrBlock, 4, 8]]
      Ipv6CidrBlock:
        !Select [1, Fn::Cidr: [!Select [0, !GetAtt VPC.Ipv6CidrBlocks], 4, 64]]
      VpcId: !Ref VPC

  RouteTableAssociationMgmt:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetMgmt

  # Subnet stack - WAN
  SubnetWan:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      AssignIpv6AddressOnCreation: true
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Select [2, Fn::Cidr: [!GetAtt VPC.CidrBlock, 4, 8]]
      Ipv6CidrBlock:
        !Select [2, Fn::Cidr: [!Select [0, !GetAtt VPC.Ipv6CidrBlocks], 4, 64]]
      VpcId: !Ref VPC

  RouteTableAssociationWan:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetWan

  # Subnet stack - LAN
  SubnetLan:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      AssignIpv6AddressOnCreation: true
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Select [3, Fn::Cidr: [!GetAtt VPC.CidrBlock, 4, 8]]
      Ipv6CidrBlock:
        !Select [3, Fn::Cidr: [!Select [0, !GetAtt VPC.Ipv6CidrBlocks], 4, 64]]
      VpcId: !Ref VPC

Outputs:
  VpcId:
    Description: VPC ID created by this stack
    Value: !Ref VPC
  RouteTableId:
    Description: Route table ID created by this stack
    Value: !Ref RouteTable
  InternetGatewayId:
    Description: Internet gateway ID created by this stack
    Value: !Ref InternetGateway
  SubnetCloudInitId:
    Description: Subnet ID for cloud-init subnet
    Value: !Ref SubnetCloudInit
  SubnetMgmtId:
    Description: Subnet ID for Mgmt subnet
    Value: !Ref SubnetMgmt
  SubnetWanId:
    Description: Subnet ID for WAN subnet
    Value: !Ref SubnetWan
  SubnetLanId:
    Description: Subnet ID for LAN subnet
    Value: !Ref SubnetLan