syslog_servers:
  # Global Syslog Server Configuration
  - name: syslog-global-test
    target:
      host: 10.1.7.2
      port: 443
      transport: tcp
      severity: alert
      lanSegment: lan-7-test
      serverStatus: true
