routing_policies:
  # Global BGP Routing Inbound and Outbound IPv4 filters configuration with Global prefix set
  - name: demo_bgp_inbound_filter
    direction: inbound
    implicit_rule: Accept
    policy_statements:
      - sequence_number: 10
        match_prefix_list: demo_prefix_list_1
        action_permit: accept
        action_set_local_preference: 100
  - name: demo_bgp_outbound_filter
    direction: outbound
    implicit_rule: Accept
    policy_statements:
      - sequence_number: 10
        match_prefix_list: demo_prefix_list_2
        action_permit: accept
        action_set_local_preference: 300
