# Sample Circuit Configuration for Graphiant Playbooks
# This file demonstrates how to configure circuits for multiple devices
# Includes examples of both IPv4 and IPv6 static routes

circuits:
  # Device 1: edge-1-sdktest
  - edge-1-sdktest:
    # Primary WAN Circuit with DIA enabled
    - circuit: c-gigabitethernet5-0-0
      description: "Primary WAN Circuit"
      upload_bandwidth: 100
      download_bandwidth: 500
      circuit_type: "circuitType_internet"
      label: "internet_dia_1"
      qos_profile: "gold25"
      qos_profile_type: "balanced"
      dia: true
      last_resort: false
    
    # Secondary WAN Circuit as last resort
    - circuit: c-gigabitethernet6-0-0
      description: "Secondary WAN Circuit"
      upload_bandwidth: 50
      download_bandwidth: 100
      circuit_type: "circuitType_internet"
      label: "internet_dia_2"
      dia: false
      last_resort: true

  # Device 2: edge-2-sdktest
  - edge-2-sdktest:
    # High-speed WAN Circuit
    - circuit: c-gigabitethernet5-0-0
      description: "High-Speed WAN"
      upload_bandwidth: 500
      download_bandwidth: 1000
      circuit_type: "circuitType_internet"
      label: "internet_dia_2"
      qos_profile: "gold10"
      qos_profile_type: "balanced"
      dia: true
      last_resort: false
      static_routes:
        # IPv4 routes
        "10.10.0.0/16":
          destination_prefix: "10.10.0.0/16"
          description: "private_network"
          administrative_distance: 2
          next_hops:
            - next_hop_address: "10.10.0.1"
        # IPv6 routes
        "2001:db8:2::/64":
          destination_prefix: "2001:db8:2::/64"
          description: "ipv6 route"
          administrative_distance: 3
          next_hops:
            - next_hop_address: "2001:db8:2::5"

  # Device 3: edge-3-sdktest
  - edge-3-sdktest:
    # Standard WAN Circuit
    - circuit: c-gigabitethernet5-0-0.1001
      description: "Standard WAN Circuit"
      upload_bandwidth: 100
      download_bandwidth: 500
      circuit_type: "circuitType_internet"
      label: "internet_dia_2"
      qos_profile: "gold25"
      qos_profile_type: "balanced"
      dia: false
      last_resort: false

    # Backup Circuit
    - circuit: c-gigabitethernet5-0-0
      description: "Backup Circuit"
      upload_bandwidth: 100
      download_bandwidth: 200
      circuit_type: "circuitType_internet"
      label: "internet_dia_3"
      qos_profile: "gold25"
      qos_profile_type: "balanced"
      dia: false
      last_resort: true

