# Configuration file for Sphinx documentation builder
# This file is auto-generated by antsibull-docs but can be customized

import sys
import os

# Add the collection path if needed
sys.path.insert(0, os.path.abspath('.'))

# Project information
project = 'Graphiant Playbooks'
copyright = '2024, Graphiant Team'
author = 'Graphiant Team'
release = '1.0.0'

# Extensions
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
]

# Theme
html_theme = 'sphinx_rtd_theme'  # or 'alabaster', 'sphinx_ansible_theme', etc.

# Options
html_static_path = ['_static']
html_show_sphinx = False

