---
- name: Verify api_base_url is available
  when: api_base_url is not defined
  ansible.builtin.fail:
    msg: "api_base_url not found"

- name: Verify bearer_token is available
  when: bearer_token is not defined
  ansible.builtin.fail:
    msg: "bearer_token not found"

- name: Verify device_id is available
  when: device_id is not defined
  ansible.builtin.fail:
    msg: "device_id not found"

- name: Get device info
  graphiant.naas.graphiant_api:
    host: "{{ api_base_url }}"
    access_token: "{{ bearer_token }}"
    method: get_device_info
    kwargs:
      device_id: "{{ device_id }}"
  register: device_info_response

- name: Flag device as not found when API returned no data
  when: device_info_response.response_data is none
  ansible.builtin.set_fact:
    device_not_found: true

- name: Get device hostname from device ID
  when: device_info_response.response_data is not none and device_info_response.response_data.device.hostname is defined
  ansible.builtin.set_fact:
    device_hostname: "{{ device_info_response.response_data.device.hostname }}"
