---
namespace: graphiant
name: graphiant_playbooks
version: 1.0.0
readme: README.md
authors:
  - Graphiant Team <support@graphiant.com>
description: Ansible collection for Graphiant NaaS network automation
license_file: LICENSE
homepage: https://www.graphiant.com
repository: https://github.com/graphiant/graphiant-playbooks
documentation: https://docs.graphiant.com/docs/graphiant-playbooks
issues: https://github.com/graphiant/graphiant-playbooks/issues
tags:
  - networking
  - naas
  - graphiant
  - automation
  - interfaces
  - circuits
  - bgp
  - routing
dependencies: {}
collections: []


